name: Telegram Notification
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "'"${TELEGRAM_CHAT_ID}"'", "text": "Se ha realizado un push al repositorio.", "disable_notification": true}' \
          https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage)

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Error: Failed to send message. HTTP Status Code: $RESPONSE"
          cat response.txt
          exit 1
        fi
