name: Telegram Notification
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: -1002087275308
      run: |
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "${TELEGRAM_CHAT_ID}", "text": "Se ha realizado un push al repositorio.", "disable_notification": true}' \
          https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage
